export const projectInfo = {
  handle: [
    {
      project: "handle",
      people: ["박준수", "박충실"],
      title: "Flex_us",
      link: "/projects/handle/1/",
    },
    {
      project: "handle",
      people: ["정민지", "권희영"],
      title: "RE-ving",
      link: "/projects/handle/2/",
    },
    {
      project: "handle",
      people: ["박지현", "황예린"],
      title: "웃는남자 오픈 런 씨어터",
      link: "/projects/handle/3/",
    },
    {
      project: "handle",
      people: ["박예진", "이나경"],
      title: "Swipe Cube",
      link: "/projects/handle/4/",
    },
    {
      project: "handle",
      people: ["박연주"],
      title: "EVERYONEDAY",
      link: "/projects/handle/5/",
    },
    {
      project: "handle",
      people: ["마정서", "양지원", "양진선"],
      title: "적정공간",
      link: "/projects/handle/6/",
    },
    {
      project: "handle",
      people: ["강민지", "한채윤"],
      title: "너나들이",
      link: "/projects/handle/7/",
    },
    {
      project: "handle",
      people: ["이시혜"],
      title: "Meet Oasis",
      link: "/projects/handle/8/",
    },
  ],
  box: [
    {
      project: "box",
      people: ["이효정"],
      title: "Look for",
      link: "/projects/box/1/",
    },
    {
      project: "box",
      people: ["이한선"],
      title: "원(源)의 교회",
      link: "/projects/box/2/",
    },
    {
      project: "box",
      people: ["김이현"],
      title: "이야기하는 도서관",
      link: "/projects/box/3/",
    },
    {
      project: "box",
      people: ["장열", "육자", "부림림"],
      title: "Healing Power",
      link: "/projects/box/4/",
    },
    {
      project: "box",
      people: ["임아림", "한유진"],
      title: "매일이 메아리",
      link: "/projects/box/5/",
    },
    {
      project: "box",
      people: ["이주영"],
      title: "MONODERN",
      link: "/projects/box/6/",
    },
    {
      project: "box",
      people: ["강동희"],
      title: "JENGA Together",
      link: "/projects/box/7/",
    },
    {
      project: "box",
      people: ["김현경"],
      title: "BOX TO BOX",
      link: "/projects/box/8/",
    },
    {
      project: "box",
      people: ["구가영", "강유정"],
      title: "The CARE",
      link: "/projects/box/9/",
    },
    {
      project: "box",
      people: ["안현정"],
      title: "SPREAD OUT",
      link: "/projects/box/10/",
    },
  ],
  frame: [
    {
      project: "frame",
      people: ["이박문", "유사동"],
      title: "안녕, 마음속에 스토리",
      link: "/projects/frame/1/",
    },
    {
      project: "frame",
      people: ["최연호"],
      title: "Ex-change",
      link: "/projects/frame/2/",
    },
    {
      project: "frame",
      people: ["곽가", "장령희"],
      title: "52Hz",
      link: "/projects/frame/3/",
    },
    {
      project: "frame",
      people: ["윤자경", "한혜인"],
      title: "레디메이드 방공호",
      link: "/projects/frame/4/",
    },
    {
      project: "frame",
      people: ["김명주", "조민경"],
      title: "흉터",
      link: "/projects/frame/5/",
    },
    {
      project: "frame",
      people: ["김미나", "김혜진", "윤수지"],
      title: "Dèsart",
      link: "/projects/frame/6/",
    },
    {
      project: "frame",
      people: ["주연성", "황상윤"],
      title: "Constellate the moment, 순간이 영원토록",
      link: "/projects/frame/7/",
    },
  ],
};
